name: Run Twitter Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Menjalankan setiap 2 jam dari jam 1 pagi sampai 11 malam
  workflow_dispatch:         # Opsional: untuk menjalankan manual dari UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Twitter bot
      run: python main.py
      env:
        CONSUMER_KEY: ${{ secrets.TWITTER_API_KEY }}
        CONSUMER_SECRET: ${{ secrets.TWITTER_API_SECRET_KEY }}
        ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
